### ISSUE TITLE
Question about sequential evaluation

### ISSUE THREAD

**Issue by xjdexjt** [facebookresearch/OrienterNet#22]
In maploc/evaluation/mapillary.py or maploc/evaluation/kitti.py, I notice the"max_init_error" in "default_cfg_sequential" is set to None or zero, which means during sequential evaluation, the map data is queried as a square area centered around real GPS position instead of a noisy GPS position. This could be unfair when compared between single frame result and sequential result. Have I understood the code right?  or did I miss something?

**Comment by Skydes** [comment]
Good question. In KITTI we use a small search space (20m radius) following the previous work of Shi et al.:
https://github.com/facebookresearch/OrienterNet/blob/71e89ebdfa489e8c3d28ec668d9dad7da2ca5988/maploc/data/kitti/dataset.py#L47-L48

For the sake of fairness, we also set the predictions outside this area to zero:
https://github.com/facebookresearch/OrienterNet/blob/71e89ebdfa489e8c3d28ec668d9dad7da2ca5988/maploc/data/kitti/dataset.py#L50
https://github.com/facebookresearch/OrienterNet/blob/71e89ebdfa489e8c3d28ec668d9dad7da2ca5988/maploc/data/dataset.py#L169-L170
https://github.com/facebookresearch/OrienterNet/blob/71e89ebdfa489e8c3d28ec668d9dad7da2ca5988/maploc/models/orienternet.py#L151-L152

In sequential mode, if we were to sample the maps with random offsets, the scores would cancel each other over the sequence and only the GT location would remain unmasked, making the localization trivial. This is solely due to the fact that the search window in small - this problem does not occur in the Mapillary or Aria evaluations. Centering the window at the GT location alleviates this and does not really make it easier for OrienterNet since it is translation equivariant - predictions are mostly unchanged, the size of the search area has much more impact.

**Comment by xjdexjt** [comment]
Thanks for the detailed explanation,  that's really solved my problem 
And this paper is really a good work :)
